// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvcsrjweaywcdelbdvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdmNzcmp3ZWF5d2NkZWxiZHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzg2NDEsImV4cCI6MjA2OTg1NDY0MX0.yWbBza9__jjk8W-u2ceNJNvaXcd44zKhlOH_J9Y2SPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});